require("prototypes.categories")
require("prototypes.categories_machinery")
require("prototypes.categories_C&R")
require("prototypes.categories_Railworld")
require("prototypes.categories_Satisfactory")
require("prototypes.lab")
require("prototypes.technology")
require("prototypes.technology_Satisfactory")